debug: add package-lock.json existence check

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -14,12 +14,18 @@ jobs:
     
     steps:
     - uses: actions/checkout@v4
+      with:
+        fetch-depth: 0
 
     - name: Use Node.js ${{ matrix.node-version }}
       uses: actions/setup-node@v4
       with:
         node-version: ${{ matrix.node-version }}
         cache: 'npm'
+
+    - name: Verify package-lock.json exists
+      run: |
+        if [ ! -f package-lock.json ]; then echo "package-lock.json not found!"; exit 1; fi
 
     - name: Test
       run: |
@@ -34,11 +40,18 @@ jobs:
       contents: read
     steps:
       - uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
       - uses: actions/setup-node@v4
         with:
           node-version: '20.x'
           registry-url: https://registry.npmjs.org/
           cache: 'npm'
+
+      - name: Verify package-lock.json exists
+        run: |
+          if [ ! -f package-lock.json ]; then echo "package-lock.json not found!"; exit 1; fi
+
       - run: npm install -g npm@latest
       - run: npm ci
       - name: Publish to NPM with Trusted Publishing
